import {
  CustomerAccount,
  CustomerAccountFormValues,
  GeneralStations,
  GeneralUser,
  StationFormValues,
  UserFormValues,
} from "common/AdminModel";
import { Mode } from "common/enums";
import moment from "moment";

/**
 * Customer Account form utils
 */

export const customerAccountInitFormValues: CustomerAccountFormValues = {
  name: "",
  identifier: "",
  city: "",
  actif: false,
  resaleRight: false,
  cardManager: false,
  exported: false,
  status: "ENABLED",
  confirmPassword: "",
  parentId: "",
  creatorAccountId: "",
  username: "",
  email: "",
  savedEmail: "",
  firstName: "",
  lastName: "",
  password: "",
  phone: "",
  paymentMethods: [
    {
      code: "",
    },
  ],
  plannedExportDate: moment().format("YYYY-MM-DDTHH:mm"),
  scheduledDate: moment().format("YYYY-MM-DDTHH:mm"),
};

export const customerAccountToFormValues = (
  customerAccount: CustomerAccount,
): CustomerAccountFormValues => {
  const {
    id,
    identifier,
    name,
    city,
    cardManager,
    creatorAccountId,
    parentId,
    resaleRight,
    exported,
    paymentMethods,
    status,
    actif,
    masterUser,
    plannedExportDate,
    scheduledDate,
  } = customerAccount;

  const {
    username,
    firstName,
    userIdentifier,
    lastName,
    email,
    phone,
  } = masterUser;

  return {
    id,
    name,
    identifier,
    savedIdentifier: identifier,
    city,
    cardManager,
    saveCardManager: cardManager,
    savedName: name,
    creatorAccountId,
    parentId,
    resaleRight,
    exported,
    status,
    actif,
    username,
    savedUsername: username,
    userIdentifier,
    savedUserIdentifier: userIdentifier,
    email,
    savedEmail: email,
    firstName,
    lastName,
    phone,
    paymentMethods,
    plannedExportDate: plannedExportDate ?? moment().format("YYYY-MM-DDTHH:mm"),
    scheduledDate: scheduledDate ?? moment().format("YYYY-MM-DDTHH:mm:ss"),
  };
};

export const formValuesToCustomerAccount = (
  values: CustomerAccountFormValues,
): CustomerAccount => {
  const {
    id,
    identifier,
    savedIdentifier,
    name,
    savedName,
    userIdentifier,
    savedUserIdentifier,
    city,
    cardManager,
    saveCardManager,
    creatorAccountId,
    parentId,
    resaleRight,
    exported,
    username,
    email,
    firstName,
    lastName,
    password,
    phone,
    paymentMethods,
    status,
    actif,
    plannedExportDate,
    scheduledDate,
  } = values;

  return {
    id,
    name: name ?? savedName,
    identifier: identifier ?? savedIdentifier,
    city,
    cardManager: cardManager ?? saveCardManager,
    creatorAccountId,
    parentId,
    resaleRight,
    exported,
    paymentMethods,
    status,
    actif,
    masterUser: {
      username,
      userIdentifier,
      email,
      firstName,
      lastName,
      password,
      phone,
    },
    plannedExportDate: plannedExportDate,
    scheduledDate: scheduledDate,
  };
};

export const userInitFormValues = {
  mode: Mode.CREATE,
  identifier: "",
  username: "",
  firstName: "",
  lastName: "",
  originalUsername: "",
  email: "",
  originalEmail: "",
  password: "",
  confirmPassword: "",
  phone: "",
  changePassword: false,
  sendSms: false,
  actif: false,
  creatorAccountId: "",
  customerAccountId: "",
  subnetMask: "",
  lastConnectionDate: "",
};

export const userToFormValues = (user: GeneralUser): UserFormValues => {
  const {
    id,
    userIdentifier,
    username,
    creatorAccountId,
    customerAccountId,
    firstName,
    lastName,
    email,
    phone,
    sendSms,
    actif,
    changePassword,
    subnetMask,
    lastConnectionDate,
  } = user;

  return {
    id,
    userIdentifier,
    creatorAccountId,
    customerAccountId,
    username,
    savedUsername: username,
    savedUserIdentifier: userIdentifier,
    email,
    savedEmail: email,
    firstName,
    lastName,
    phone,
    sendSms,
    actif,
    changePassword,
    subnetMask,
    lastConnectionDate,
  };
};

export const formValuesToUser = (values: UserFormValues): GeneralUser => {
  const {
    id,
    userIdentifier,
    creatorAccountId,
    customerAccountId,
    username,
    email,
    firstName,
    lastName,
    phone,
    password,
    sendSms,
    actif,
    changePassword,
    lastConnectionDate,
  } = values;

  return {
    id,
    userIdentifier,
    username,
    creatorAccountId,
    customerAccountId,
    sendSms,
    changePassword,
    actif,
    email,
    firstName,
    lastName,
    password,
    phone,
    lastConnectionDate,
  };
};

export const stationInitFormValues: StationFormValues = {
  name: "",
  identifier: "",
  address: "",
  city: "",
  creatorCustomerAccountName: "",
  customerAccountName: "",
  creatorAccountId: "",
  account: "",
  controllerType: "",
  actif: false,
  controllerPts: {
    ptsId: "",
    phone: "",
    controllerType: "",
    userController: {
      username: "",
      password: "",
    },
  },
  phone: "",
  connection: "",
  createdDate: "",
  password: "",
  countryId: 0,
  customerAccountId: "",
  savedCustomerAccountId: "",
  cordonneesGps: "",
  modeAffectation: "",
  journal: "",
};

export const stationToFormValues = (
  station: GeneralStations,
): StationFormValues => {
  const {
    id,
    identifier,
    name,
    address,
    city,
    creatorCustomerAccountName,
    customerAccountName,
    creatorAccountId,
    account,
    controllerType,
    actif,
    controllerPts,
    phone,
    connection,
    createdDate,
    password,
    countryId,
    customerAccountId,
    cordonneesGps,
    modeAffectation,
    journal,
  } = station;

  return {
    id,
    identifier,
    savedIdentifier: identifier,
    name,
    address,
    city,
    creatorCustomerAccountName,
    customerAccountName,
    creatorAccountId,
    account,
    controllerType,
    actif,
    controllerPts,
    phone,
    connection,
    createdDate,
    password,
    countryId,
    customerAccountId,
    savedCustomerAccountId: customerAccountId,
    cordonneesGps,
    modeAffectation,
    journal,
  };
};

export const formValuesToStation = (
  values: StationFormValues,
): GeneralStations => {
  const {
    id,
    identifier,
    savedIdentifier,
    name,
    address,
    city,
    creatorCustomerAccountName,
    customerAccountName,
    creatorAccountId,
    account,
    controllerType,
    actif,
    controllerPts,
    phone,
    connection,
    createdDate,
    password,
    countryId,
    customerAccountId,
    savedCustomerAccountId,
    cordonneesGps,
    modeAffectation,
    journal,
  } = values;

  return {
    id,
    identifier: identifier ?? savedIdentifier,
    name,
    address,
    city,
    creatorCustomerAccountName,
    customerAccountName,
    creatorAccountId,
    account,
    controllerType,
    actif,
    controllerPts,
    phone,
    connection,
    createdDate,
    password,
    countryId,
    customerAccountId: customerAccountId ?? savedCustomerAccountId,
    cordonneesGps,
    modeAffectation,
    journal,
  };
};
